version: "3"

services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    volumes:
      - ./influxdb/scripts:/docker-entrypoint-initdb.d:ro
      - influx_data:/var/lib/influxdb
    networks:
      - server-net

  telegraf:
    image: telegraf:1.25
    container_name: telegraf
    restart: unless-stopped
    depends_on:
      - influxdb
    volumes:
      - ./telegraf:/etc/telegraf:ro
    networks:
      - server-net

  mqtt_bridge:
    build: ./mqtt_bridge
    container_name: mqtt_bridge
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      # Замените 192.168.3.10 на IP вашей Linux B
      MQTT_HOST: "192.168.3.10"
      MQTT_PORT: "1883"
      INFLUX_HOST: "influxdb"
      INFLUX_DB: "sensors"
    networks:
      - server-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/:/etc/grafana/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - server-net

volumes:
  influx_data: {}
  grafana_data: {}

networks:
  server-net: {}
