[global_tags]

[agent]
  interval        = "10s"
  round_interval  = true
  metric_batch_size   = 1000
  metric_buffer_limit = 10000
  flush_interval  = "10s"
  flush_jitter    = "0s"
  precision       = "0s"
  hostname        = ""
  omit_hostname   = false

# Output: InfluxDB (alias контейнера, не IP)
[[outputs.influxdb]]
  urls     = ["http://influxdb:8086"]
  database = "sensors"
  skip_database_creation = true
  username = "telegraf"
  password = "telegraf"

# Input: MQTT Consumer
# Замените 192.168.3.10 на IP вашей Linux B (машина с Mosquitto)
[[inputs.mqtt_consumer]]
  servers   = ["tcp://192.168.3.10:1883"]
  topics    = ["sensors/#"]
  topic_tag = "topic"
  data_format = "value"
  data_type   = "float"
